# Generated by Django 5.1.6 on 2025-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X URL'),
        ),
    ]
